import { spawn } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { getConfig } from "./config/config.js";
import { parseCliEnvironmentArgument, stripEnvironmentArguments } from "./config/cli.js";

const allowedViteCommands = new Set(["dev", "build", "preview"]);
const VITE_MODE_PREFIX = "companyhelm-";

function toWebSocketUrl(graphqlApiUrl) {
  const parsed = new URL(graphqlApiUrl);
  parsed.protocol = parsed.protocol === "https:" ? "wss:" : "ws:";
  return parsed.toString();
}

function toRuntimeConfig(config) {
  const supabaseConfig = config.auth.supabase || {
    url: "",
    anonKey: "",
    tokenStorageKey: "supabase.auth.token",
  };

  return {
    api: {
      graphqlApiUrl: config.api.graphqlApiUrl,
      graphqlWebSocketUrl: toWebSocketUrl(config.api.graphqlApiUrl),
      runnerGrpcTarget: config.api.runnerGrpcTarget,
    },
    authProvider: config.authProvider,
    auth: {
      companyhelm: {
        tokenStorageKey: config.auth.companyhelm.tokenStorageKey,
      },
      supabase: {
        url: supabaseConfig.url,
        anonKey: supabaseConfig.anonKey,
        tokenStorageKey: supabaseConfig.tokenStorageKey,
      },
    },
  };
}

function writeRuntimeConfigModule(config) {
  const generatedDirPath = resolve(process.cwd(), "src", "generated");
  const runtimeConfigModulePath = resolve(generatedDirPath, "runtime-config.js");
  const runtimeConfig = toRuntimeConfig(config);
  const nextRuntimeModuleContents = [
    "// Auto-generated by scripts/vite.js. Do not edit manually.",
    `export const runtimeConfig = ${JSON.stringify(runtimeConfig, null, 2)};`,
    "",
  ].join("\n");

  mkdirSync(generatedDirPath, { recursive: true });
  let currentRuntimeModuleContents = "";
  try {
    currentRuntimeModuleContents = readFileSync(runtimeConfigModulePath, "utf8");
  } catch {
    currentRuntimeModuleContents = "";
  }

  if (currentRuntimeModuleContents !== nextRuntimeModuleContents) {
    writeFileSync(runtimeConfigModulePath, nextRuntimeModuleContents, "utf8");
  }
}

function toViteMode(environment) {
  return `${VITE_MODE_PREFIX}${String(environment || "").trim()}`;
}

export function resolveViteCommand(argv) {
  const command = String(argv[0] || "").trim();
  const extraArgs = argv.slice(1).filter(Boolean);
  const unsupportedArgs = stripEnvironmentArguments(extraArgs);

  if (!command) {
    throw new Error("Missing Vite command. Expected one of: dev, build, preview.");
  }
  if (!allowedViteCommands.has(command)) {
    throw new Error(`Unsupported Vite command "${command}". Expected one of: dev, build, preview.`);
  }
  if (unsupportedArgs.length > 0) {
    throw new Error(
      "Vite CLI options are disabled. Configure host/port/API values in config/<environment>.yaml."
    );
  }

  return command;
}

function startVite(argv) {
  const viteCommand = resolveViteCommand(argv);
  const environment = parseCliEnvironmentArgument(argv.slice(1));
  const config = getConfig(environment);
  writeRuntimeConfigModule(config);
  const viteMode = toViteMode(environment);

  const viteBinPath = resolve(process.cwd(), "node_modules", "vite", "bin", "vite.js");
  const child = spawn(process.execPath, [viteBinPath, viteCommand, "--mode", viteMode], {
    stdio: "inherit",
  });

  child.on("error", (error) => {
    console.error(error);
    process.exitCode = 1;
  });

  child.on("exit", (code, signal) => {
    if (signal) {
      process.kill(process.pid, signal);
      return;
    }
    process.exitCode = code ?? 0;
  });
}

const isMainModule = process.argv[1]
  ? import.meta.url === pathToFileURL(process.argv[1]).href
  : false;

if (isMainModule) {
  startVite(process.argv.slice(2));
}
